SEGEMENTS_PER_BEAT = 12
BEAT_SEGMENT_ACCEPTED_ROUNDING_ERROR = 1/50
MIDI_NOTE_COUNT = 128
MIDI_NOTE_AND_SILENCE_COUNT = MIDI_NOTE_COUNT + 1
# Do about four measures of 4/4 for window slide.
WINDOW_SLIDE_SIZE = SEGEMENTS_PER_BEAT * 4 * 4
